name: "designed for playâ„¢ games"
description: ""
masthead:
  image: "/assets/designedforplay.logo-01.png"
  height: "64"
author: johnson earls
email: designedforplaygames@gmail.com

copyright:
  by: johnson earls
  start: 2012-12-02

license:
  type: "All rights reserved"
  file: false

# social links
twitter_username: designedforplay
github_username:  designedforplaygames

show_excerpts: true # set to false to remove excerpts on the homepage

remote_theme: fongandrew/hydeout

timezone: America/Los_Angeles

kramdown:
  parse_block_html: true

# for use in templates
game_statuses:
  published: Published
  testing: Playtesting
  development: In Development
  idea: Idea Stage
  shelved: On the Shelf
